### ISSUE TITLE
Using ACCELERATE Framework for Numpy Calculations in matrix multiplication

### ISSUE THREAD

**Issue by niravlekinwala** [alexziskind1/machine_tests#1]
Hi Alex, 

I watched your latest video (https://youtu.be/UNgqtYtOIJk?), and you used this code to highlight the NumPy performance. Following are some things that I'd like to highlight.

The code you're currently using needs to be optimised to use the matrix multiplication accelerator built into all Apple Silicon Processors. It offloads heavy tasks to the accelerator. The time taken by my M1 MacBook Air with and without Accelerate framework is as follows. Not only the time reduces by more than half, the load on CPU is drastically lower.

Output from the existing environment -- NumPy without Accelerate Framework
```
Matrix multiplication of size 16000x16000 took 169.24 seconds
python run.py  472.34s user 228.08s system 405% cpu 2:52.69 total
```

Output from the proposed solution -- NumPy with Accelerate Framework
```
Matrix multiplication of size 16000x16000 took 75.06 seconds
python run.py  33.19s user 24.93s system 74% cpu 1:18.05 total
```

I propose the following changes to readme.md: Install numpy using `pip install --no-binary :all: --no-use-pep517 numpy==1.25.2` to your readme. The difference in NumPys can be observed using `np.show_config()`

The output of `np.show_config()` from the proposed solution -- NumPy with Accelerate Framework (observe the 'accelerate_info' is present, which is usually absent with base installation)
```
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
blas_ssl2_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
accelerate_info:
    extra_compile_args = ['-I/System/Library/Frameworks/vecLib.framework/Headers']
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
blas_opt_info:
    extra_compile_args = ['-I/System/Library/Frameworks/vecLib.framework/Headers']
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
lapack_ssl2_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
openblas_clapack_info:
  NOT AVAILABLE
flame_info:
  NOT AVAILABLE
lapack_opt_info:
    extra_compile_args = ['-I/System/Library/Frameworks/vecLib.framework/Headers']
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
Supported SIMD extensions in this NumPy install:
    baseline = NEON,NEON_FP16,NEON_VFPV4,ASIMD
    found = ASIMDHP,ASIMDDP
    not found = ASIMDFHM
```

Output of `np.show_config()` the existing environment -- NumPy without Accelerate Framework
```
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/nirav/opt/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/nirav/opt/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/nirav/opt/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/nirav/opt/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
Supported SIMD extensions in this NumPy install:
    baseline = NEON,NEON_FP16,NEON_VFPV4,ASIMD
    found = ASIMDHP,ASIMDDP
    not found = ASIMDFHM
```

I hope you try the solution and let me know if you see any improvement.

Regards,
Nirav

**Comment by peterlionelnewman** [comment]
came here to say this:
`conda install -c conda-forge numpy "libblas=*=*accelerate"`

**Comment by alexziskind1** [comment]
Thanks for the info @niravl and @peterlionelnewman

**Comment by jatinkushwaha14** [comment]
Hey Nirav, newbie here i was trying to setup numpy with accelerate frame work on the same machine mac air m1 i got time taken to be 69.99 seconds which is way less than what you had shown. Here's my output along with np.show_config() included in run.py

(venv-metal) (base) jatinkushwaha@JATINs-MacBook-Air PYTHON MAIN % /Users/jatinkushwaha/anaconda3/envs/venv-metal/bin
/python3.11 "/Users/jatinkushwaha/My-Files/PYTHON MAIN/Test/test.py"
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
blas_ssl2_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
accelerate_info:
    extra_compile_args = ['-I/System/Library/Frameworks/vecLib.framework/Headers']
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
blas_opt_info:
    extra_compile_args = ['-I/System/Library/Frameworks/vecLib.framework/Headers']
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
lapack_ssl2_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
openblas_clapack_info:
  NOT AVAILABLE
flame_info:
  NOT AVAILABLE
lapack_opt_info:
    extra_compile_args = ['-I/System/Library/Frameworks/vecLib.framework/Headers']
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
Supported SIMD extensions in this NumPy install:
    baseline = NEON,NEON_FP16,NEON_VFPV4,ASIMD
    found = ASIMDHP,ASIMDDP
    not found = ASIMDFHM
Matrix multiplication of size 16000x16000 took 69.99 seconds
